//AMBIENTAIS

SELECT * FROM ESTRUTURAS WHERE CONTA = '01' AND LEFT(SUBCONTA,4) ='0107' ORDER BY CONTA,SUBCONTA

/*
DROP TABLE AMBIENTAIS;
GO
CREATE TABLE AMBIENTAIS AS
SELECT * FROM ESTRUTURAS WHERE  CONTA = '01' AND LEFT(SUBCONTA,4) ='0107' ORDER BY CONTA,SUBCONTA
GO
*/


UPDATE AMBIENTAIS SET CONTA = '08', SUBCONTA = SUBSTRING(SUBCONTA,3), NIVEL = NIVEL - 1
GO
UPDATE AMBIENTAIS SET SUBCONTA = '08' || SUBSTRING(SUBCONTA,3);
GO
UPDATE AMBIENTAIS SET TIPO = 'C' WHERE NIVEL = 1
GO
DELETE FROM estruturas WHERE CONTA = '08'
GO
INSERT INTO estruturas
 SELECT * FROM AMBIENTAIS ORDER BY CONTA,SUBCONTA
GO

