//CONSUMIDOR

SELECT * FROM ESTRUTURAS WHERE CONTA = '01' AND LEFT(SUBCONTA,4) ='0108' ORDER BY CONTA,SUBCONTA

/*
DROP TABLE CONSUMIDOR;
GO
CREATE TABLE CONSUMIDOR AS
SELECT * FROM ESTRUTURAS WHERE  CONTA = '01' AND LEFT(SUBCONTA,4) ='0108' ORDER BY CONTA,SUBCONTA
GO
*/


UPDATE CONSUMIDOR SET CONTA = '09', SUBCONTA = SUBSTRING(SUBCONTA,3), NIVEL = NIVEL - 1
GO
UPDATE CONSUMIDOR SET SUBCONTA = '09' || SUBSTRING(SUBCONTA,3);
GO
UPDATE CONSUMIDOR SET TIPO = 'C' WHERE NIVEL = 1
GO
DELETE FROM estruturas WHERE CONTA = '09'
GO
INSERT INTO estruturas
 SELECT * FROM CONSUMIDOR ORDER BY CONTA,SUBCONTA
GO

