//CONTABILIDADE

SELECT * FROM ESTRUTURAS WHERE CONTA = '01' AND LEFT(SUBCONTA,4) ='0101' ORDER BY CONTA,SUBCONTA

/*
DROP TABLE CONTABIL;
GO
CREATE TABLE CONTABIL AS
SELECT * FROM ESTRUTURAS WHERE  CONTA = '01' AND LEFT(SUBCONTA,4) ='0101' ORDER BY CONTA,SUBCONTA
*/


UPDATE CONTABIL SET CONTA = '02', SUBCONTA = SUBSTRING(SUBCONTA,3), NIVEL = NIVEL - 1
GO
UPDATE CONTABIL SET SUBCONTA = '02' || SUBSTRING(SUBCONTA,3);
GO
UPDATE CONTABIL SET TIPO = 'C' WHERE NIVEL = 1
GO
DELETE FROM estruturas WHERE CONTA = '02'
GO
INSERT INTO estruturas
 SELECT * FROM CONTABIL ORDER BY CONTA,SUBCONTA
GO

