//FISCAL

SELECT * FROM ESTRUTURAS WHERE CONTA = '01' AND LEFT(SUBCONTA,4) ='0102' ORDER BY CONTA,SUBCONTA

/*
DROP TABLE FISCAL;
GO
CREATE TABLE FISCAL AS
SELECT * FROM ESTRUTURAS WHERE  CONTA = '01' AND LEFT(SUBCONTA,4) ='0102' ORDER BY CONTA,SUBCONTA
GO
*/


UPDATE FISCAL SET CONTA = '03', SUBCONTA = SUBSTRING(SUBCONTA,3), NIVEL = NIVEL - 1
GO
UPDATE FISCAL SET SUBCONTA = '03' || SUBSTRING(SUBCONTA,3);
GO
UPDATE FISCAL SET TIPO = 'C' WHERE NIVEL = 1
GO
DELETE FROM estruturas WHERE CONTA = '03'
GO
INSERT INTO estruturas
 SELECT * FROM FISCAL ORDER BY CONTA,SUBCONTA
GO



//
update estruturas set subconta = '0102010401' , nivel = 5 where subconta = '01020105';
go
update estruturas set subconta = '0102010402' , nivel = 5 where subconta = '01020106';
go

DELETE FROM ATIVIDADES