//MARCAS

SELECT * FROM ESTRUTURAS WHERE CONTA = '01' AND LEFT(SUBCONTA,4) ='0106' ORDER BY CONTA,SUBCONTA

/*
DROP TABLE MARCAS;
GO
CREATE TABLE MARCAS AS
SELECT * FROM ESTRUTURAS WHERE  CONTA = '01' AND LEFT(SUBCONTA,4) ='0106' ORDER BY CONTA,SUBCONTA
GO
*/


UPDATE MARCAS SET CONTA = '07', SUBCONTA = SUBSTRING(SUBCONTA,3), NIVEL = NIVEL - 1
GO
UPDATE MARCAS SET SUBCONTA = '07' || SUBSTRING(SUBCONTA,3);
GO
UPDATE MARCAS SET TIPO = 'C' WHERE NIVEL = 1
GO
DELETE FROM estruturas WHERE CONTA = '07'
GO
INSERT INTO estruturas
 SELECT * FROM MARCAS ORDER BY CONTA,SUBCONTA
GO

