//PENHORES

SELECT * FROM ESTRUTURAS WHERE CONTA = '01' AND LEFT(SUBCONTA,4) ='0110' ORDER BY CONTA,SUBCONTA

/*
DROP TABLE PENHORES;
GO
CREATE TABLE PENHORES AS
SELECT * FROM ESTRUTURAS WHERE  CONTA = '01' AND LEFT(SUBCONTA,4) ='0110' ORDER BY CONTA,SUBCONTA
GO
*/


UPDATE PENHORES SET CONTA = '11', SUBCONTA = SUBSTRING(SUBCONTA,3), NIVEL = NIVEL - 1
GO
UPDATE PENHORES SET SUBCONTA = '11' || SUBSTRING(SUBCONTA,3);
GO
UPDATE PENHORES SET TIPO = 'C' WHERE NIVEL = 1
GO
DELETE FROM estruturas WHERE CONTA = '11'
GO
INSERT INTO estruturas
 SELECT * FROM PENHORES ORDER BY CONTA,SUBCONTA
GO

