//SEGURANCA

SELECT * FROM ESTRUTURAS WHERE CONTA = '01' AND LEFT(SUBCONTA,4) ='0108' ORDER BY CONTA,SUBCONTA

/*
DROP TABLE SEGURANCA;
GO
CREATE TABLE SEGURANCA AS
SELECT * FROM ESTRUTURAS WHERE  CONTA = '01' AND LEFT(SUBCONTA,4) ='0108' ORDER BY CONTA,SUBCONTA
GO
*/


UPDATE SEGURANCA SET CONTA = '09', SUBCONTA = SUBSTRING(SUBCONTA,3), NIVEL = NIVEL - 1
GO
UPDATE SEGURANCA SET SUBCONTA = '09' || SUBSTRING(SUBCONTA,3);
GO
UPDATE SEGURANCA SET TIPO = 'C' WHERE NIVEL = 1
GO
DELETE FROM estruturas WHERE CONTA = '09'
GO
INSERT INTO estruturas
 SELECT * FROM SEGURANCA ORDER BY CONTA,SUBCONTA
GO

