//SOCIETARIA

SELECT * FROM ESTRUTURAS WHERE CONTA = '01' AND LEFT(SUBCONTA,4) ='0103' ORDER BY CONTA,SUBCONTA

/*
DROP TABLE SOCIETARIA;
GO
CREATE TABLE SOCIETARIA AS
SELECT * FROM ESTRUTURAS WHERE  CONTA = '01' AND LEFT(SUBCONTA,4) ='0103' ORDER BY CONTA,SUBCONTA
GO
*/


UPDATE SOCIETARIA SET CONTA = '04', SUBCONTA = SUBSTRING(SUBCONTA,3), NIVEL = NIVEL - 1
GO
UPDATE SOCIETARIA SET SUBCONTA = '04' || SUBSTRING(SUBCONTA,3);
GO
UPDATE SOCIETARIA SET TIPO = 'C' WHERE NIVEL = 1
GO
DELETE FROM estruturas WHERE CONTA = '04'
GO
INSERT INTO estruturas
 SELECT * FROM SOCIETARIA ORDER BY CONTA,SUBCONTA
GO

