    SELECT   CAB.ID_EMPRESA
            ,CAB.ENTRADA
            ,CAB.SAIDA
            ,CAB.ID_CLIENTE
            ,CAB.ID_CARRO
            ,CAB.ID_COND
            ,CAB.HORAS_SERVICO
            ,CAB KM
            ,CAB.OBS
            ,CAB.LUCRO
            ,CAB.ID_COND_PGTO
            ,CAB.MAO_OBRA
            ,CAB.MAO_OBRA_VLR
            ,CAB.PECAS_VLR
            ,CAB.USER_INSERT
            ,CAB.USER_UPDATE
            ,CLI.CODIGO     AS CLI_CODIGO
            ,CLI.CNPJ_CPF   AS CLI_CNPJ_CPF
            ,CLI.TEL1       AS CLI_TEL1
            ,CLI.EMAIL      AS CLI_EMAIL
            ,CAR.PLACA      AS CAR_PLACA
            ,CAR.MARCA      AS CAR_MARCA
            ,CAR.COR        AS CAR_COR
            ,CAR.ANO        AS CAR_ANO
            ,COALESCE(COND.ID,0)  AS COND_ID
            ,COALESCE(COND.DESCRICAO,'') AS COND_DESCRICAO
    FROM OS_CAB CAB
    INNER JOIN CLIENTES  CLI  ON CLI.ID_EMPRESA  = CAB.ID_EMPRESA  AND CLI.CODIGO  = CAB.ID_CLIENTE
    INNER JOIN OS_CAR    CAR  ON CAR.ID_EMPRESA  = CAB.ID_EMPRESA  AND CAR.PLACA   = CAB.ID_CARRO
    LEFT  JOIN CONDICOES COND ON COND.ID_EMPRESA = CAB.ID_EMPRESA  AND COND.ID     = CAB.ID_COND
GO

//OS_DET
SELECT   DET.ID_EMPRESA
        ,DET.ID_OS
        ,DET.ITEM
        ,DET.QTD
        ,DET.DESCRICAO
        ,DET.VALOR
        ,DET.USER_INSERT
        ,DET.USER_UPDATE  
FROM OS_DET DET

//CAR
SELECT   DET.ID_EMPRESA
        ,DET.PLACA
        ,DET.MARCA
        ,DET.COR
        ,DET.ANO
        ,DET.USER_INSERT
        ,DET.USER_UPDATE 
FROM OS_CAR CAR

SELECT COND.ID_EMPRESA
     , COND.PLACA
     , COND.MARCA
     , COND.COR
     , COND.ANO
     , COND.USER_INSERT
     , COND.USER_UPDATE
FROM CONDICOES COND


INSERT INTO public.os_car(id_empresa, placa, marca, cor, ano, user_insert, user_update) 
	VALUES(0, '', '', '', '', 0, 0)
GO



INSERT INTO public.condicoes(ID_EMPRESA, ID, DESCRICAO, NRO_PARCELAS, INTER1, INTER2, USER_INSERT, USER_UPDATE) 
	VALUES(0, 0, '', 0, '', '', 0, 0)
GO


SELECT   CAR.PLACA ,MARCA.DESCRICAO AS MARCA_DESCRICAO ,CAR.MODELO ,CAR.COR ,CAR.ANO 
FROM OS_CAR CAR 
INNER JOIN MARCAS MARCA ON MARCA.ID_EMPRESA = CAR.ID_EMPRESA AND MARCA.ID = CAR.ID_MARCA   
ORDER BY CAR.ID_EMPRESA  ,  CAR.PLACA  



 INSERT INTO OS_CAR (ID_EMPRESA, PLACA, ID_MARCA, MODELO, COR, ANO, USER_INSERT, USER_UPDATE)  VALUES(1,'IIA8888',1,'8888', 88','88888888',3,0)  RETURNING * 