SELECT CAB.ID,CAB.SISTEMA,DET.DESCRICAO,DET.CFOP,EXC.BAS_ICMS_EXC AS "BAS_ICMS_EXC = (1)",DET.PER_ICMS AS "PER_ICMS = (2)",DET.PER_PIS AS "PER_PIS = (4)",DET.PER_COF AS "PER_COF = (4)"
      ,ROUND((EXC.BAS_ICMS_EXC * (DET.PER_ICMS/100)),2)                      AS  "(1) * (2) = (3)"
      ,ROUND(ROUND((EXC.BAS_ICMS_EXC * (DET.PER_ICMS/100)),4) * (DET.PER_PIS/100),4)  AS  "(3) * (4)PIS =(5)"
      ,ROUND(ROUND((EXC.BAS_ICMS_EXC * (DET.PER_ICMS/100)),4) * (DET.PER_COF/100),4)  AS  "(3) * (4)COF =(5)"
FROM   NFE_DET DET
INNER  JOIN NFE_DET_BASICMSEXC EXC  ON EXC.ID = DET.ID AND EXC.NRO_LINHA = DET.NRO_LINHA 
INNER  JOIN NFE_CAB CAB ON CAB.ID = DET.ID
WHERE DET.ID = 10
ORDER BY DET.ID,DET.NRO_LINHA 
GO

SELECT * FROM SELIC ORDER BY ANO,MES
GO
