SELECT  PROJ.ID            AS PROJ_ID
       ,PROJ.ID_CLIENTE    AS ID_CLIENTE
       ,CLI.RAZAO          AS CLI_RAZAO
       ,CLI.GRU_ECONO      AS GRUPO_ID
       ,GRUPO.RAZAO        AS GRUPO_RAZAO
       ,PROJ.DESCRICAO     AS PROJ_DESCRICAO
       ,PROJ.ID_DIRETOR    AS PROJ_ID_DIRETOR
       ,DIR.RAZAO          AS DIR_RAZAO
       ,PROJ.HORASVE       AS HORAS_VEN
       ,PROJ.VALOR         AS PROJ_VALOR
       ,to_char(PROJ.DATAPROJ,  'DD/MM/YYYY') AS DATA_PROJ
       ,to_char(PROJ.DATAENC,  'DD/MM/YYYY')  AS DATA_ENCER
       ,SUM(
          CASE 
             WHEN TIT.DATA_VENCTO < NOW() AND TIT.DATA_PAGTO IS NULL THEN TIT.VALOR
             ELSE                            0
          END) AS TOTAL_VENCIDO
       ,SUM(
          CASE 
             WHEN TIT.DATA_VENCTO >= NOW() AND TIT.DATA_PAGTO IS NULL THEN TIT.VALOR
             ELSE                            0
          END) AS TOTAL_NAO_VENCIDO
       ,SUM(
          CASE 
             WHEN TIT.DATA_PAGTO IS NOT NULL THEN TIT.VALOR
             ELSE                            0
          END) AS TOTAL_PAGTO
FROM TITULOS_PROJETO TIT
INNER JOIN PROJETOS PROJ       ON TIT.ID_EMPRESA = PROJ.ID_EMPRESA AND TIT.ID_PROJETO = PROJ.ID 
INNER JOIN CLIENTES CLI        ON CLI.ID_EMPRESA = PROJ.ID_EMPRESA AND CLI.ID = PROJ.ID_CLIENTE
INNER JOIN GRUPOS_ECO GRUPO    ON GRUPO.ID_EMPRESA = PROJ.ID_EMPRESA AND GRUPO.ID = CLI.GRU_ECONO
INNER JOIN USUARIOS DIR        ON DIR.ID_EMPRESA = PROJ.ID_EMPRESA AND DIR.ID = PROJ.ID_DIRETOR
WHERE PROJ.VALOR > 0 
GROUP BY  
       PROJ.ID
       ,PROJ.ID_CLIENTE
       ,CLI.RAZAO
       ,CLI.GRU_ECONO
       ,GRUPO.RAZAO
       ,PROJ.DESCRICAO
       ,PROJ.ID_DIRETOR
       ,DIR.RAZAO
       ,PROJ.HORASVE
       ,PROJ.VALOR
       ,to_char(PROJ.DATAPROJ,  'DD/MM/YYYY')
       ,to_char(PROJ.DATAENC,  'DD/MM/YYYY') 
ORDER BY PROJ.ID
GO


//TOTAL POR grupo
SELECT 
     TAB.GRUPO_RAZAO
    ,SUM(TAB.PROJ_VALOR) AS VALOR_PROJETO
    ,SUM(HORAS_VEN)      AS HORAS_VEN
    ,SUM(TAB.TOTAL_VENCIDO) AS TOTAL_VENCIDO
    ,SUM(TAB.TOTAL_NAO_VENCIDO) AS TOTAL_NAO_VENCIDO
    ,SUM(TAB.TOTAL_PAGTO)  AS TOTAL_PAGTO
 FROM
(SELECT  PROJ.ID            AS PROJ_ID
       ,PROJ.ID_CLIENTE    AS ID_CLIENTE
       ,CLI.RAZAO          AS CLI_RAZAO
       ,CLI.GRU_ECONO      AS GRUPO_ID
       ,GRUPO.RAZAO        AS GRUPO_RAZAO
       ,PROJ.DESCRICAO     AS PROJ_DESCRICAO
       ,PROJ.ID_DIRETOR    AS PROJ_ID_DIRETOR
       ,DIR.RAZAO          AS DIR_RAZAO
       ,PROJ.HORASVE       AS HORAS_VEN
       ,PROJ.VALOR         AS PROJ_VALOR
       ,to_char(PROJ.DATAPROJ,  'DD/MM/YYYY') AS DATA_PROJ
       ,to_char(PROJ.DATAENC,  'DD/MM/YYYY')  AS DATA_ENCER
       ,SUM(
          CASE 
             WHEN TIT.DATA_VENCTO < NOW() AND TIT.DATA_PAGTO IS NULL THEN TIT.VALOR
             ELSE                            0
          END) AS TOTAL_VENCIDO
       ,SUM(
          CASE 
             WHEN TIT.DATA_VENCTO >= NOW() AND TIT.DATA_PAGTO IS NULL THEN TIT.VALOR
             ELSE                            0
          END) AS TOTAL_NAO_VENCIDO
       ,SUM(
          CASE 
             WHEN TIT.DATA_PAGTO IS NOT NULL THEN TIT.VALOR
             ELSE                            0
          END) AS TOTAL_PAGTO
FROM TITULOS_PROJETO TIT
INNER JOIN PROJETOS PROJ       ON TIT.ID_EMPRESA = PROJ.ID_EMPRESA AND TIT.ID_PROJETO = PROJ.ID 
INNER JOIN CLIENTES CLI        ON CLI.ID_EMPRESA = PROJ.ID_EMPRESA AND CLI.ID = PROJ.ID_CLIENTE
INNER JOIN GRUPOS_ECO GRUPO    ON GRUPO.ID_EMPRESA = PROJ.ID_EMPRESA AND GRUPO.ID = CLI.GRU_ECONO
INNER JOIN USUARIOS DIR        ON DIR.ID_EMPRESA = PROJ.ID_EMPRESA AND DIR.ID = PROJ.ID_DIRETOR
WHERE PROJ.VALOR > 0 
GROUP BY  
       PROJ.ID
       ,PROJ.ID_CLIENTE
       ,CLI.RAZAO
       ,CLI.GRU_ECONO
       ,GRUPO.RAZAO
       ,PROJ.DESCRICAO
       ,PROJ.ID_DIRETOR
       ,DIR.RAZAO
       ,PROJ.HORASVE
       ,PROJ.VALOR
       ,to_char(PROJ.DATAPROJ,  'DD/MM/YYYY')
       ,to_char(PROJ.DATAENC,  'DD/MM/YYYY') 
ORDER BY PROJ.ID) 
AS TAB
GROUP BY  TAB.GRUPO_RAZAO
ORDER BY TAB.GRUPO_RAZAO


//Valor Recebido Por Mes
SELECT  to_char(TIT.DATA_PAGTO,  'MM/YYYY') AS DATA_PAGTO
       ,SUM(
          CASE 
             WHEN TIT.DATA_PAGTO IS NOT NULL THEN TIT.VALOR
             ELSE                            0
          END) AS TOTAL_PAGTO
FROM TITULOS_PROJETO TIT
INNER JOIN PROJETOS PROJ       ON TIT.ID_EMPRESA = PROJ.ID_EMPRESA AND TIT.ID_PROJETO = PROJ.ID 
INNER JOIN CLIENTES CLI        ON CLI.ID_EMPRESA = PROJ.ID_EMPRESA AND CLI.ID = PROJ.ID_CLIENTE
INNER JOIN GRUPOS_ECO GRUPO    ON GRUPO.ID_EMPRESA = PROJ.ID_EMPRESA AND GRUPO.ID = CLI.GRU_ECONO
INNER JOIN USUARIOS DIR        ON DIR.ID_EMPRESA = PROJ.ID_EMPRESA AND DIR.ID = PROJ.ID_DIRETOR
WHERE to_char(TIT.DATA_PAGTO,  'YYYY') = '2023'
GROUP BY to_char(TIT.DATA_PAGTO,  'MM/YYYY')
ORDER BY to_char(TIT.DATA_PAGTO,  'MM/YYYY') 
