INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'INTELLI IND DE TERMINAIS ELETR. LTDA', 'INTELLI', '2023-2-8', 63, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ATLANTE BALAS E CARAMELOS LTDA', 'ATLANTE', '2023-2-8', 10, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'COPPERSTEEL BIMETALICOS LTDA', 'COPPERSTEEL', '2023-2-8', 63, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERVEJARIA PETROPOLIS S/A', 'CPSA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'COOPERATIVA VEILING HOLAMBRA', 'VEILING', '2023-2-8', 112, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ANHANGUERA COM. DE FERRAMENTAS LTDA', 'ANHANGUERA', '2023-2-8', 8, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'LINC INDUSTRIAL E COML DE TECIDOS LTDA', 'LINC', '2023-2-8', 73, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'COOPERFER - COOPER. PROD. ART. FERRAM.', 'COOPERFER', '2023-2-8', 30, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'LOGSERVE LOGISTICA, SERVS. ARMAZEN. LTDA', 'LOGSERVE', '2023-2-8', 74, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERVEJARIA PETROPOLIS CENTRO OESTE LTDA', 'CPCO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ZUQUETTI & MARZOLA PART. E REPRES. LTDA', 'ZM', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BERMAD BRASIL IND. VALVULAS LTDA', 'BERMAD', '2023-2-8', 16, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CARLOS EDUARDO PRUDENTE CORREA', 'CARLOS EDUARDO', '2023-2-8', 24, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'MECANICA BONFANTI S/A', 'BONFANTI', '2023-2-8', 18, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BRAGA COMERCIO E INDUSTRIA LTDA', 'BRAGA', '2023-2-8', 19, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'TECNIPLAS TUBOS E CONEXOES LTDA', 'TECNIPLAS', '2023-2-8', 107, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GM DOS REIS INDUSTRIA E COMERCIO LTDA', 'GM DOS REIS', '2023-2-8', 54, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SONABYTE ELETRONICA LTDA', 'SONABYTE', '2023-2-8', 101, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'COL - CENTRO OESTE LOGÍSTICA LTDA', 'COL', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'INTERNATIONAL PLASTICS IND & COM LTDA', 'IPL', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'NAANDAN JAIN BRASIL IND COM E IRR LTDA', 'NAANDAN', '2023-2-8', 81, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'JUSHI GROUP (BZ) SINOSIA COMP. MAT. LTDA', 'JUSHI', '2023-2-8', 69, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BALLUFF CONTROLES ELETRICOS LIMITADA', 'BALLUFF', '2023-2-8', 13, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'HIDROALL DO BRASIL LTDA - SLIGON', 'SLIGON', '2023-2-8', 99, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERVEJARIA PETROPOLIS DA BAHIA LTDA', 'CPBA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERVEJARIA PETRÓPOLIS DE PERNAMBUCO LTDA', 'CPPE', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ALTHAIA S/A INDUSTRIA FARMACÊUTICA', 'ALTHAIA', '2023-2-8', 6, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'EQUALIV PHARMA IND. COM. E DISTR. LTDA', 'EQUALIV', '2023-2-8', 6, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'HIDROALL DO BRASIL LTDA', 'HIDROALL', '2023-2-8', 59, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'VALUE PHARMA PARTICIPAÇÕES LTDA', 'VALUE LTDA', '2023-2-8', 6, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'VALUE PHARMA INVESTIMENTOS E PARTIC LTDA', 'VALUE S/A', '2023-2-8', 6, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'NIPRO MEDICAL LTDA', 'NIPRO', '2023-2-8', 83, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SALBEGO LABORATÓRIO FARMACÊUTICO LTDA', 'SALBEGO', '2023-2-8', 83, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ABRANJO GERAÇÃO DE ENERGIA S/A', 'ABRANJO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CANAA GERACAO DE ENERGIA S/A', 'CANAÃ', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CARNAUBA GERACAO DE ENERGIA S/A', 'CARNAUBA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ELECTRA POWER GERAÇÃO DE ENERGIA S/A', 'ELECTRA POWER', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'TAMBORIL ENERGETICA S/A', 'TAMBORIL', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'MCM QUIMICA INDUSTRIAL LTDA', 'MCM', '2023-2-8', 78, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SOCEIDADE REG ENS SAUDE LTDA', 'SLM', '2023-2-8', 100, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DROGARIA GALANTI DE NOVA IGUAÇU LTDA', 'GALANTI', '2023-2-8', 48, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'STAR SU INDUSTRIA DE FERRAMENTAS LTDA', 'STAR SU', '2023-2-8', 102, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'INTERMÁQUINAS COM. DE MAQ. E EQUIP.', 'INTERMÁQUINAS', '2023-2-8', 64, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'UNICMAQ BRASIL COM. DE MAQ. E INSTRUMENTOS', 'UNICMAQ', '2023-2-8', 111, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CP GLOBAL TRADING LLP', 'CP GLOBAL', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SIX LABEL IND. GRAFICA DA AMAZONIA LTDA.', 'SIX LABEL', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERVEJARIA PETROPOLIS DO PARANÁ LTDA', 'CPPR', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GP MALTING', 'GP MALTING', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'FIRST BRAND', 'FIRST BRAND', '2023-2-8', 6, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SIMIONATO AUDITORES INDEPENDENTES', 'SIMIONATO', '2023-2-8', 97, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ACCENTURE DO BRASIL LTDA', 'ACCENTURE', '2023-2-8', 3, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GEA EQUIPAMENTOS E SOLUÇÕES S/A', 'GEA', '2023-2-8', 50, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'RM SISTEMAS', 'RM', '2023-2-8', 90, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GUEPAVA S/A', 'GUEPAVA', '2023-2-8', 57, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ASTEN & CIA LTDA', 'ASTEN ', '2023-2-8', 8, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DUCATI & ASSOCIADOS LTDA', 'DUCATI', '2023-2-8', 41, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'D. OLIVIERI FOMENTO MERCANTIL LTDA', 'D. OLIVIERI', '2023-2-8', 31, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'MSI GLOBAL ALLIANCE', 'MSI', '2023-2-8', 80, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BRL – RÓTULOS ADESIVOS LTDA', 'BRL', '2023-2-8', 21, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'MÉRITO AUDITORES INDEPENDENTES', 'MÉRITO', '2023-2-8', 79, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BAR DA PRAIA RESTAURANTE LTDA - EPP', 'BAR DA PRAIA', '2023-2-8', 14, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GP COMERCIALIZADORA DE ENERGIA LTDA.', 'GP ENERGIA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GP PARTICIPAÇÕES EMPREENDIMENTO S.A.', 'GP PARTICIPAÇÕES', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GP PRIME ASSESSORIA LTDA', 'GP PRIME', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GP MAXLUZ HOLDING S.A.', 'GP MAXLUZ', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'HIDRELECTRA MEGASUL LTDA', 'MEGASUL', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'COTRIN EMPREENDIMENTOS E ADM. DE BENS LTDA. ', 'COTRIN', '2023-2-8', 8, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GAH PARTICIPACOES LTDA.', 'GAH', '2023-2-8', 8, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ICARO GERACAO DE ENERGIA EOLICA LTDA', 'ICARO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ALTO CHOPIM ENERGIA S.A. - ACESA', 'ALTO CHOPIM', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ARROIO MULADA ENERGÉTICA LTDA.', 'ARROIO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ARUANÃ GERAÇÃO DE ENERGIA S.A.', 'ARUANÃ', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CAPÃO ALTO GERAÇÃO DE ENERGIA S.A.', 'CAPÃO ALTO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CEREJEIRA GERAÇÃO DE ENERGIA S.A.', 'CEREJEIRA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERTEL FOZ DO JACUTINGA GERAÇÃO DE ENERGIA S.A.', 'CERTEL FOZ DO JACUTINGA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERTEL MOINHO VELHO GERAÇÃO DE ENERGIA S.A.', 'CERTEL MOINHO VELHO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERTEL OLARIA GERAÇÃO DE ENERGIA S.A.', 'CERTEL OLARIA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERTEL VALE DO LEITE GERAÇÃO DE ENERGIA S.A.', 'CERTEL VALE DO LEITE', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CERTEL VALE FUNDO GERAÇÃO DE ENERGIA S.A.', 'CERTEL VALE FUNDO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'COLINAS DE MONTE NEGRO ENERGIA EÓLICA S.A.', 'COLINAS', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DONA LÍDIA GERAÇÃO DE ENERGIA S.A.', 'DONA LÍDIA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'EMÍLIO VESCOVI GERAÇÃO DE ENERGIA S.A.', 'EMÍLIO VESCOVI', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ESTRELA GERAÇÃO DE ENERGIA S.A.', 'ESTRELA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'FÁBRICA GERAÇÃO DE ENERGIA S.A.', 'FÁBRICA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'FAZENDA RIO BONITO GERAÇÃO DE ENERGIA S.A.', 'FAZENDA RIO BONITO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'HIDRELÉTRICA GUABIJU S.A.', 'HIDRELÉTRICA GUABIJU', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ITAJAÍ-AÇU GERAÇÃO DE ENERGIA S.A.', 'ITAJAÍ-AÇU', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'JAGUATIRICA GERAÇÃO DE ENERGIA S.A.', 'JAGUATIRICA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'JEQUITIBÁ GERAÇÃO DE ENERGIA S.A.', 'JEQUITIBÁ', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'LOBO-GUARÁ GERAÇÃO DE ENERGIA S.A.', 'LOBO-GUARÁ', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'NOVA ALIANÇA GERAÇÃO DE ENERGIA S.A.', 'NOVA ALIANÇA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ONÇA PINTADA GERAÇÃO DE ENERGIA S.A.', 'ONÇA PINTADA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'PEDRAS BRANCAS GERAÇÃO DE ENERGIA S.A.', 'PEDRAS BRANCAS', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'PINHAL DA SERRA GERAÇÃO DE ENERGIA S.A.', 'PINHAL DA SERRA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'RIO CARREIRO GERAÇÃO DE ENERGIA S.A.', 'RIO CARREIRO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'RIO RIBEIRA GERAÇÃO DE ENERGIA S.A.', 'RIO RIBEIRA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'LABMASS LAB.-LAB.ANÁLISE QUÍ.CONS.TREINA LTDA - EPP', 'LABMASS LABORATORY', '2023-2-8', 72, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ANDORINHA COMÉRCIO E DISTRIBUIÇÃO LTDA.', 'ANDORINHA MEDICAMENT', '2023-2-8', 7, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'PHENOM CAPITAL ADM. DE RECURSOS S/A.', 'PHENOM', '2023-2-8', 85, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CONTLINE ASSESSORIA E CONSULTORIA CONTÁBIL LTDA', 'CONTLINE ', '2023-2-8', 28, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CASCO DO BRASIL LTDA.', 'CASCO', '2023-2-8', 25, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CASA PORTUGUESA LTDA - EPP', 'POSTO PORTUGUÊS ', '2023-2-8', 86, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GATA MÍDIA LOCAÇÃO DE ESPAÇOS PARA PUBLICIDADE LTDA.', 'GATA MÍDIA', '2023-2-8', 49, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SILVIO ANTONIO FRANÇA - CAMPINAS', 'SA VIDRO', '2023-2-8', 93, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'H R S TECNOLOGIA INDUSTRIAL LTDA', 'H R S', '2023-2-8', 58, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SETE PRODUTOS E LIMPEZA LTDA', 'SETE', '2023-2-8', 96, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'PJS CENTRO DE TEC. CEL. E CRIOPRESERVAÇÃO LTDA', 'PJS', '2023-2-8', 86, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'RODVAS COMÉRCIO E REPRES. LTDA  - ME', 'RODVAS', '2023-2-8', 91, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DECORLIT PRODUTOS DE CONCRETO LTDA.', 'DECORLIT', '2023-2-8', 34, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ED ROBSON MORELATO', 'CISÃO(GRUPO OMEGA)', '2023-2-8', 27, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'STEPAN INDÚSTRIA DE MÁQUINAS E MOTORES LTDA.', 'STEPAN', '2023-2-8', 103, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ESACOL CONTABILIDADE E ASSESSORIA LTDA', 'ESACOL', '2023-2-8', 42, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'LMA LOCAÇÕES DE EQUIPAMENTOS LTDA', 'AVENTA', '2023-2-8', 12, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'COMERCIAL W COM.DE PROD. PARA RESTAURANTES EIRELI ', 'COMERCIAL W', '2023-2-8', 23, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CONSULCAMP AUDITORIA E ASSESSORIA LTDA.', 'CONSULCAMP', '2023-2-8', 28, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'FUNDAÇÃO EST AGRARIOS LUIZ DE QUEIROZ', 'FEALQ', '2023-2-8', 46, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BRASSARIA AMPOLIS COM. DE BEBIDAS LTDA.', 'BRASSARIA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'A X INVESTIMENTOS EM EMPRESAS LTDA.', 'A X', '2023-2-8', 1, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'RESIVIDRO EQUIPAMENTOS INDUSTRIAIS LTDA', 'RESIVIDRO', '2023-2-8', 89, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'WAYTAX SERVIÇOS EMPRESARIAS LTDA', 'WAYTAX', '2023-2-8', 114, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'OPETRA INDÚSTRIA E COMÉRCIO DE TRAVESSEIROS LTDA.', 'OPETRA', '2023-2-8', 84, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'LUITEX MÁQUINAS E FERRAMENTAS LTDA', 'LUITEX', '2023-2-8', 75, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'EXPRESSO ITATIBA LTDA', 'EXP. ITATIBA', '2023-2-8', 45, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DRIP-PLAN IND. E COM. DE EQUIP. IRRIGACAO LTDA', ' DRIP-PLAN', '2023-2-8', 40, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ASSOCIAÇÃO DOS PROPRIETÁRIOS SWISS PARK', 'SWISS PARK', '2023-2-8', 105, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'MARCO ORLANDI', 'MARCO ORLANDI', '2023-2-8', 77, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'EUROP ASSISTANCE BRASIL SERVICOS DE ASSISTENCIA S/A', 'EUROP ASSISTANCE', '2023-2-8', 43, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GP BOUTIQUE PETROPOLIS LTDA ', 'GP BOUTIQUE', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ALTEX COMÉRCIO DE CALÇADOS LTDA ME E OUTROS.', 'ALTEX', '2023-2-8', 5, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DANILO APARECIDO PEDROSO', 'DANILO - PERITO', '2023-2-8', 32, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ZUCOLLO AUTO PARTS IND. COM. EXP. IMP. LTDA', 'ZUCOLLO', '2023-2-8', 117, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ULTRA MÁQUINAS COML. DE FERRAMENTAS LTDA', 'ULTRA MÁQUINAS', '2023-2-8', 109, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DR. ALEX SUCARIA BATISTA', 'DR. ALEX', '2023-2-8', 39, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'TDSP - PARTICIPAÇÕES LTDA.', 'TDSP', '2023-2-8', 106, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GHBP ADVOGADOS', 'GHBP', '2023-2-8', 51, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GRUPO DINMAP', 'DINMAP', '2023-2-8', 37, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BIOMETAL INDÚSTRIA E COMÉRCIO EIRELI ', 'BIOMETAL', '2023-2-8', 17, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GARCIA DE LIMA SOCIEDADE DE ADVOGADOS', 'DE LIMA', '2023-2-8', 33, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'L.I.G. GLOBAL SER. TEC. IMPL. SIS. TEL. E ENERGIA LTDA', 'L.I.G GLOBAL', '2023-2-8', 70, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ROZAC COMERCIO IMPORTACAO E EXPORTACAO DE PRODUTOS TEXTEIS S.A', 'ROZAC', '2023-2-8', 92, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'VIAMETAL PARTICIPACOES LTDA.', 'VIAMETAL', '2023-2-8', 113, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'WEM EQUIPAMENTOS ELETRÔNICOS LTDA', 'WEM', '2023-2-8', 115, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ABC EMPREENDIMENTOS IMOBILIARIOS LTDA', 'ABC', '2023-2-8', 2, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GLOBAL COMMUNITIES BRASIL', 'GLOBAL', '2023-2-8', 53, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DENIS CIMAF BRASIL MAQUINAS INDUSTRIAIS EIRELI', 'DENIS CIMAF', '2023-2-8', 35, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SINTERCAN FERRAMENTARIA LTDA.', 'SINTERCAN', '2023-2-8', 98, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CINERGIS AGRONEGÓCIOS LTDA.', 'CINERGIS', '2023-2-8', 26, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'J.L.COELHO EMPREEND. E PARTICIPAÇÕES LTDA', 'J.L. COELHO', '2023-2-8', 66, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'HUGO HENRIQUE DE ALMEIDA COTRIN', 'HUGO', '2023-2-8', 8, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SIQUEIRA FERREIRA COMÉRCIO DE CARNES EIRELI', 'CODERSU', '2023-2-8', 23, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'JOSÉ CARLOS PAREJA', 'JOSÉ CARLOS', '2023-2-8', 68, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BRENO ACIMAR PACHECO CORREA', 'BRENO - PERITO', '2023-2-8', 20, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'M KILLIAN AGRÍCOLA LTDA', 'M KILLIAN', '2023-2-8', 76, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'AGUETONI TRANSPORTES LTDA', 'AGUETONI', '2023-2-8', 4, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GUADALAJARA S/A INDÚSTRIA DE ROUPAS', 'GUADALAJARA', '2023-2-8', 56, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'RAINHA INDÚSTRIA E COMÉRCIO DE ALIMENTOS EIRELI ', 'RAINHA', '2023-2-8', 88, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'EXCENTAL IMPORTAÇÃO E EXPORTAÇÃO LTDA.', 'EXCENTAL', '2023-2-8', 44, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'AUDIOESP – AUDITORIA E CONSULTORIA S/S', 'AUDIOESP', '2023-2-8', 11, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BERCROM GRÁFICA E EDITORA LTDA.', 'BERCROM', '2023-2-8', 15, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SAPORE S.A.', 'SAPORE', '2023-2-8', 94, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'HORTISHOP SISTEMAS DE IRRIGACAO LTDA', 'HORTISHOP', '2023-2-8', 60, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'JOÃO AUGUSTO SALLA', 'JOÃO AUGUSTO', '2023-2-8', 67, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'FERREIRA PIRES ADVOGADOS', 'FERREIRA PIRES', '2023-2-8', 47, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GP IMOVEIS SP LTDA', 'GP IMOVEIS SP', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GP IMOVEIS MT LTDA', 'GP IMOVEIS MT', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'UMAFLEX IND MOVEIS COLCHOES E ESPUMAS LTDA', 'UMAFLEX', '2023-2-8', 110, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'L.I.V SANEAMENTO E PARTICIPAÇÕES LTDA', 'L.I.V', '2023-2-8', 71, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SIMIONATO AUDITORES - SÃO PAULO', 'SIMIONATO - SP', '2023-2-8', 97, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SWINT – INTELIGÊNCIA & INVESTIGAÇÃO CORPORATIVA LTDA', 'SWINT', '2023-2-8', 104, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'DOMINGUES ADVOGADOS ASSOCIADOS', 'DOMINGUES', '2023-2-8', 38, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'NEXT – SOLUÇÕES IMOBILIÁRIAS LTDA', 'NEXT', '2023-2-8', 82, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'IAS CONSTRUTORA LTDA', 'IAS', '2023-2-8', 62, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'IRRIGAPLAN IND. E COM. DE EQUIP.DE IRR. LTDA.', 'IRRIGAPLAN', '2023-2-8', 65, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'GIULIANA COMÉRCIO DE FLORES E ARRANJOS LTDA', 'GIULIANA', '2023-2-8', 52, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'TONUTRI BRASIL EIRELI – ME', 'TONUTRI', '2023-2-8', 108, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'X TRADE IMPORTADORA E COMÉRCIO LTDA', 'X TRADE', '2023-2-8', 116, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BWB EMBALAGENS LTDA', 'BWB EMBALAGENS', '2023-2-8', 22, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BWB PRODUTOS LTDA', 'BWB PRODUTOS', '2023-2-8', 22, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SAMPUTENSILI PARTICIPAÇÕES DO BRASIL LTDA.', 'SAMPUTENSILI', '2023-2-8', 102, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'SDO COM. IMP. E LOC. DE EQUIP. LTDA.', 'SDO', '2023-2-8', 95, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'ZUQUETE EMPREENDIMENTOS E PARTICIPAÇOES LTDA.', 'ZM EMPREEND.', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'AGROPECUARIA RETIRO DAS PEDRAS LTDA', 'AGRO RETIRO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'BWS MARCAS LTDA', 'BWS', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'MALTERIA ORIENTAL SOCIEDAD ANONIMA – MOSA', 'MALTERIA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'NOVA GUAPORE AGRICOLA LTDA', 'NOVA GUAPORE', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'MINEFER DEVELOPMENT S.A', 'MINEFER', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'TRIANA BUSINESS S.A.', 'TRIANA', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'CANAA  GERAÇAO DE ENERGIA RENOVAVEL S.A.', 'CANAÃ RENOVAVEL', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'TAMOIO MINERAÇÃO S/A', 'TAMOIO', '2023-2-8', 55, 17, 0);
go
INSERT INTO public.clientes(id_empresa,  razao, fantasi,cadastr,  gru_econo, user_insert, user_update) 	VALUES(1,'UNICARDIO-UNID. CARDIO DE URGENCIA E METODOS DIAGNOSTICOS LTDA', 'HOSP CORAÇÃO', '2023-2-8', 61, 17, 0);
go

SELECT * FROM CLIENTES
