SELECT PROJ.ID,PROJ.ID_CLIENTE
       ,CLI.RAZAO
       ,PROJ.DESCRICAO
       ,PROJ.ID_DIRETOR
       ,DIR.RAZAO
       ,PROJ.OBJETO
       ,PROJ.OBS
       ,PROJ.HORASVE
       ,PROJ.horasexec
       ,CASE
           WHEN COALESCE((SELECT COUNT(*) FROM ATIVIDADES ATIV WHERE ATIV.ID_EMPRESA  = PROJ.ID_EMPRESA  AND ATIV.ID_PROJETO = PROJ.ID AND ATIV.TIPO = 'S'),0) > 0 THEN 'SIM'
           ELSE 'NÃO'
        END AS TEM_ATIVIDADE
FROM PROJETOS PROJ
INNER JOIN CLIENTES CLI ON CLI.ID_EMPRESA = PROJ.ID_EMPRESA AND CLI.ID = PROJ.ID_CLIENTE
INNER JOIN USUARIOS DIR ON DIR.ID_EMPRESA = PROJ.ID_EMPRESA AND DIR.ID = PROJ.ID_DIRETOR
WHERE PROJ.ID = 231
ORDER BY PROJ.ID
GO


SELECT PROJ.ID,PROJ.ID_CLIENTE
       ,CLI.RAZAO
       ,PROJ.DESCRICAO
       ,PROJ.ID_DIRETOR
       ,DIR.RAZAO
       ,PROJ.HORASVE
       ,PROJ.horasexec
       ,APO.id AS NRO_LANC     
       ,APO.id_subconta  
       ,ESTRU.DESCRICAO     
       ,APO.id_resp
       ,RESP.RAZAO AS REPONSAVEL
       ,APO.id_exec     
       ,EXEC.RAZAO AS EXECUTOR
       ,APO.inicial              
       ,APO.final  
       ,APO.horasapon  
       ,to_char(APO.horasapon,'09.99')  
       ,function_HSrxagenal(APO.horasapon)          
       ,APO.obs
FROM PROJETOS PROJ
INNER JOIN CLIENTES       CLI ON CLI.ID_EMPRESA = PROJ.ID_EMPRESA AND CLI.ID = PROJ.ID_CLIENTE
INNER JOIN USUARIOS       DIR ON DIR.ID_EMPRESA = PROJ.ID_EMPRESA AND DIR.ID = PROJ.ID_DIRETOR
INNER JOIN apons_execucao APO ON APO.ID_EMPRESA = PROJ.ID_EMPRESA AND APO.ID_PROJETO = PROJ.ID
INNER JOIN ESTRUTURAS     ESTRU  ON ESTRU.ID_EMPRESA = PROJ.ID_EMPRESA  AND ESTRU.conta = APO.ID_CONTA  AND ESTRU.versao = APO.ID_CONTA_VERSAO AND ESTRU.subconta = ID_SUBCONTA
INNER JOIN USUARIOS       RESP   ON RESP.ID_EMPRESA  =PROJ.ID_EMPRESA  AND RESP.ID = APO.ID_RESP 
INNER JOIN USUARIOS       EXEC   ON EXEC.ID_EMPRESA  =PROJ.ID_EMPRESA  AND EXEC.ID = APO.ID_EXEC
WHERE PROJ.ID = 231
ORDER BY PROJ.ID
       ,APO.id_subconta  
       ,ESTRU.DESCRICAO  
       ,RESP.RAZAO
       ,EXEC.RAZAO
       ,APO.inicial      
GO

