TRUNCATE nfe_cab_e  RESTART  IDENTITY ;
GO
TRUNCATE nfe_det_e  RESTART  IDENTITY ;
GO
TRUNCATE controle_e RESTART  IDENTITY ;
GO
TRUNCATE fechamento RESTART  IDENTITY ;
GO

SELECT * FROM nfe_det_e where operacao = 'E' and vlr_cof = 0 and bas_icms = 0

SELECT * FROM nfe_cab_e


SELECT * FROM nfe_det_e where id = 1 order by nro_linha

SELECT   CAB.ID_GRUPO,  CAB.ID,  CAB.PLANILHA,  CLI.EMPRESA, CLI.CNPJ_CPF, CAB.QTD,  CAB.VLR_CONTABIL,  CAB.BAS_ICMS,  CAB.VLR_ICMS,  CAB.BAS_PIS,  CAB.VLR_PIS,  CAB.BAS_COF,  CAB.VLR_COF,  CAB.NRO_LINHA,  CAB.USUARIOINCLUSAO,  CAB.USUARIOATUALIZACAO, CAB.DATA_CRIACAO, CAB.DATA_FECHAMENTO, CAB.STATUS 
FROM NFE_CAB_E CAB  
INNER JOIN CLIENTES CLI ON CLI.ID_GRUPO = CAB.ID_GRUPO AND CLI.CNPJ_CPF = CAB.CNPJ
ORDER BY CAB.ID  
LIMIT 1000 OFFSET 0 

DELETE FROM nfe_cab_e WHERE ID = 1
GO
DELETE FROM nfe_det_e WHERE ID = 1
GO
