TRUNCATE TABLE contacontabil RESTART IDENTITY;
go
TRUNCATE TABLE movicab       RESTART IDENTITY;
go
TRUNCATE TABLE movidet       RESTART IDENTITY;
go
TRUNCATE TABLE saldo         RESTART IDENTITY;
go
